config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root "users#index"
  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:index, :new, :show, :create, :destroy] 
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    return unless user.present?

    can :manage, User, id: user.id
    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id
    can :create, Like

    return unless user.role == 'admin'

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates :text, presence: true

  after_save :increase_counter
  before_destroy :decrease_counter

  private

  def increase_counter
    post.increment!(:comments_counter)
  end

  def decrease_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_counter

  private

  def update_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, inverse_of: 'post', dependent: :destroy
  has_many :comments, inverse_of: 'post', dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true

  after_save :increase_counter
  before_destroy :decrease_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def increase_counter
    author.increment!(:posts_counter)
  end

  def decrease_counter
    author.decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: 'author_id', inverse_of: 'author', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', inverse_of: 'author', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', inverse_of: 'author', dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :role)
    end
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments

    respond_to do |format|
      format.json { render json: @comments }
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = @post

    respond_to do |format|
      if @comment.save
        # Rendering view for html request
        format.html do
          flash[:success] = 'New comment added successfully!'
          redirect_to user_post_url(@post.author, @post)
        end
        # Rendering json for json request
        format.json { render json: @comment, status: :created }
      else
        format.html do
          flash[:error] = 'Comment upload failed!'
          redirect_to new_user_post_comment_url(@post.author, @post)
        end

        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_back_or_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(author: current_user, post: @post)
    if @like.save
      flash[:success] = "Gave a like to #{@post.title}!"
    else
      flash[:error] = 'Adding a like failed!'
    end
    redirect_to user_post_path(@post.author, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
    @current_user = current_user

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(params[:id])
    @current_user = current_user
  end

  def new
    @user = current_user
    @post = Post.new
    @current_user = current_user
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    respond_to do |format|
      if @post.save
        format.html do
          flash[:success] = 'New post uploaded successfully!'
          redirect_to user_post_url(current_user, @post)
        end

        format.json { render json: @post, status: :created }
      else
        format.html do
          flash[:error] = 'Post upload failed! Please try again'
          redirect_to new_user_post_post_url(current_user)
        end

        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to user_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @current_user = current_user
  end

  def show
    @user = User.find(params[:id])
    @current_user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<section>
    <%= render "shared/post_card", post: @post %>
    <%= form_with model: [@user, @post, @comment], class: "comment-form" do |f| %>
        <div class="input-container">
            <%= f.label :text, "Write Your Comment" %>
            <%= f.text_area :text, rows: 2, required: true %>
        </div>
        <%= f.submit "Add Comment", class: "submit-btn" %>
    <% end %>
    <% if flash[:error] %>
        <div class="alert alert-error" >
            <%= flash[:error] %>
        </div>
    <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "main" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <% if notice %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: [@user, @post], class: "post-form" do |f| %>
<div class="input-container" >
    <%= f.label :title %>
    <%= f.text_field :title, required: true %>
</div>

<div class="input-container" >
    <%= f.label :text, "Content" %>
    <%= f.text_area :text, size: "60x10", required: true %>
</div>

<%= f.submit "Create New Post", class: "submit-btn" %>
<% end %>

app/views/posts/index.html.erb
<section>
    <%= render "shared/header", current_user: @current_user %>
    <%= render "shared/user_card", user: @user %>
    
    <% if @posts.empty? %>
        <p>There is no post yet.</p>
    <% end %>

    <% @posts.each do |post| %>
        <%= render "shared/post_card", post: post %>
        <%= render "shared/comment_box", comments: post.recent_comments, current_user: @current_user %>
    <% end %>

    <button class="link-btn" type="button">Pagination</button>

</section>

app/views/posts/new.html.erb
<section>
    <%= render "shared/header", current_user: @current_user %>
    <h1>Creating New Post</h1>

    <%= render "form", post: @post, user: @user %>

    <% if flash[:error] %>
        <div class="alert alert-error" >
            <%= flash[:error] %>
        </div>
    <% end %>
</section>

app/views/posts/show.html.erb
<section>
    <%= render "shared/header", current_user: @current_user %>
    <div class="post-container">
        <header>
            <h2 class="post-title"><%= @post.title %></h2>
            <div class="post-info">
                <h3 class="post-author">Author: <%= link_to @post.author.name, user_path(@post.author) %></h3>
                <span>Comments: 💬<%= @post.comments_counter || 0 %></span>
                <span>Likes: 💖<%= @post.likes_counter || 0 %></span>
            </div>
        <div class="post-btn-bar">
            <% if can? :destroy, @post %>
                <%= form_with model: [@current_user, @post], method: :delete do |f| %>
                    <%= f.submit "Delete", class: "btn warn-btn" %>
                <% end %>
            <% end %>
        </div>
        </header>

        <p class="post-content">
            <%= @post.text %>
        </p>

        <div class="post-btn-bar">
        <% if @current_user %>
            <%= form_with model: [@current_user, @post, Like.new] do |f| %>
                <%= f.submit 'Give Like', class: "post-btn" %>
            <% end %>
            <%= link_to "Add Comment", new_user_post_comment_path(@post.author, @post), class: "post-btn" %>
        <% end %>
        </div>
        
    </div>

    <% if flash[:success] %>
        <div class="alert alert-success" >
            <%= flash[:success] %>
        </div>
    <% end %>

    <%= render "shared/comment_box", comments: @post.comments, current_user: @current_user %>
</section>

app/views/shared/_comment_box.html.erb
<div class="comment-container">
  <h4>Comments</h4>

  <ul class="comment-list">

  <% if comments.empty? %>
      <small>No one has commented yet.</small>
  <% end %>

  <% comments.each do |comment| %>
      <li class="comment-item">
          <div class="commentor-info">
              <span class="avatar" style="background-color: <%= %w[green red purple orange].sample %>"><%= comment.author.name[0].upcase %></span>
              <p><%= comment.author.name %></p>
          </div>

          <div class="comment-text">
              <p><%= comment.text %></p>
          </div>

          <% if can? :destroy, comment %>
          <div class="remove-comment">
              <%= form_with model: [@current_user, comment.post, comment], method: :delete do |f| %>
                  <%= f.submit "Remove", class: "btn warn-btn" %>
              <% end %>
          </div>
          <% end %>

      </li>
  <% end %>

  </ul>
</div>

app/views/shared/_header.html.erb
<header class="main-header">
    <div class="brand" >
    <%= link_to "Blogify", root_path%>
    </div>

    <% if user_signed_in? %>
        <div class="profile-container">
            <%= link_to current_user.name, user_path(current_user) %>
            <span class="user-icon"><%= current_user.name[0].upcase %></span>
        </div>
    <% else %>
        <div>
        <%= link_to 'Register', new_user_registration_path, class: "btn primary-btn" %>
        <%= link_to 'Log In', new_user_session_path, class: 'btn primary-btn' %>
        </div>
    <% end %>
    
</header>

app/views/shared/_post_card.html.erb
<div class="post-card">
    <h3><%= link_to post.title, user_post_path(post.author, post), class: "post-card-title" %></h3>
    <p><%= post.text[0..200] %>...</p>
    <p class="post-info">
        <span>Comments: 💬<%= post.comments_counter || 0 %></span>
        <span>Likes: 💖<%= post.likes_counter || 0 %></span>
    </p>
</div>

app/views/shared/_user_card.html.erb
<div class="user-card">
    <div class="user-photo">
        <% if user.photo %>
            <img src="<%= user.photo %>" alt="profile">
        <% else %>
            <img src="<%= "https://randomuser.me/api/portraits/men/#{rand(1..200)}.jpg" %>" alt="profile">
        <% end %>
    </div>
    <div class="user-info">
    <header class="user-header">
        <h2><%= link_to user.name, user_path(user) %></h2>
        <span class="role-badge"><%= user.role || "member" %></span>
    </header>

        <p>Number of Posts: <%= user.posts_counter || 0 %></p>
    </div>
</div>

app/views/users/index.html.erb
<section>
    <%= render "shared/header", current_user: @current_user %>
    <div class="tool-bar">
    <% if user_signed_in? %>
        <%= link_to "+ New Post", new_user_post_path(@current_user), class: "btn primary-btn" %>
    <% else %>
        <p>Join Blogify to create new post!</p>
    <% end %>
    </div>
    <div class="users-container">
    <% @users.each do |user| %>
        <%= render "shared/user_card", user: user %>
    <% end %>
    </div>
</section>

app/views/users/show.html.erb
<section>
    <%= render "shared/header", current_user: @current_user %>
    <div class="user-detail">
        <%= render "shared/user_card", user: @user %>
        
        <% if @current_user == @user %>
            <%= form_with url: destroy_user_session_path, method: :delete do |f| %>
                <%= f.submit "Log Out", class: "btn warn-btn" %>
            <% end %>
        <% end %>
        <div class="user-bio">
            <h3>Bio</h3>
            <p><%= @user.bio %></p>
        </div>
    </div>

    <div class="recent-posts">
        <% @user.recent_posts.each do |post| %>
            <%= render "shared/post_card", post: post %>
        <% end %>
    </div>

    <%= link_to "See All Posts", user_posts_path(@user), class: "link-btn" %>
</section>